name: publish

on:
  push:
    branches: main

jobs:
  build:
    uses: alves-dev/actions/.github/workflows/build-docker.yml@main
    with:
      image-name: ghcr.io/alves-dev/synclife-orchestrator-subscription