name: publish

on:
  push:
    branches: main

jobs:
  publish-docker-image:
    env:
      IMAGE_TAG: $(date +%Y%m%d)  # Cria uma tag com a data de execução
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'

      - name: Build and Push Docker image
        uses: alves-dev/infra/.github/workflows/build-docker.yml@main
        with:
          image-name: ghcr.io/alves-dev/synclife-orchestrator-subscription